### ISSUE TITLE
IndexError: Invalid key index 16.

### ISSUE THREAD

**Issue by flajann2** [timothycrosley/streamdeck-ui#129]
Occasionally, the indexing becomes corrupted for some reason.
 ```
Traceback (most recent call last):                                                                                      17:11:42
  File "/home/alveric/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/usr/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 663, in start
    api.render()
  File "/usr/lib/python3.9/site-packages/streamdeck_ui/api.py", line 312, in render
    deck.set_key_image(button_id, image)
  File "/usr/lib/python3.9/site-packages/StreamDeck/Devices/StreamDeckOriginalV2.py", line 169, in set_key_image
    raise IndexError("Invalid key index {}.".format(key))
IndexError: Invalid key index 16.
python3: os/threads_posix.h:58: usbi_mutex_destroy: Zusicherung »pthread_mutex_destroy(mutex) == 0« nicht erfüllt.
fish: Job 1, 'streamdeck &' terminated by signal SIGABRT (Abbruch)
```

I've noticed problems like this before, but this time I am using 2 Streamdecks, different sizes.

https://gist.github.com/flajann2/5d4fcf29b8b59796adf318cd012bc67c

**Comment by flajann2** [comment]
Note that if I unplug the smaller deck, the bigger one comes up OK.
Also, if I plug the smaller deck back in while Streamdeck is running, it doesn't load the icons. If I then stop Streamdeck and rerun it with both decks plugged in, the exception as you see it above happens.

**Comment by dodgyrabbit** [comment]
Awaiting feedback on v 2.0.1 in issue #206

**Comment by dodgyrabbit** [comment]
Reopening this case and documenting my findings, as there are similar problems mentioned in #35, #167 and #253.

The first two pages (page 0 and 1) for the streamdeck have extra entries. There **should** be exactly 15.

![image](https://user-images.githubusercontent.com/518187/189464208-02ee1491-1af8-47b2-95bb-010378e9b1be.png)

As can be seen here, there are exactly as many as for the bigger StreamDeck (32 in total).

Somehow we are increasing the page configuration for the smaller deck incorrectly. This leads to the `IndexError: Invalid key index 16` since it's trying to set a button that does not exist.

**Comment by Data-007** [comment]
Hi
#253 fixed
--
Data

**Comment by dodgyrabbit** [comment]
@flajann2 I now have a better understanding of what is happening here, but I'm unable to recreate. It's possible that it was a bug in older versions. If you are still routinely having this problem, please reopen this case with any relevant details (what you did prior to the index error coming back). Thanks!
