### ISSUE TITLE
Chained unix commands in command field

### ISSUE THREAD

**Issue by lhayhurst** [timothycrosley/streamdeck-ui#132]
Hi, I'm trying to do something pretty simple, which is run this command:

```bash
wmctrl -a firefox  && xdotool key alt+1
```

This changes focus to firefox, then switches over to the first tab. 

It looks like it is only executing the first part of the command -- that is, switching focus to firefox. Running it in the shell successfully switches focus to firefox and then switches to tab1.

Is this not possible using streamdeck? My os is ubuntu 20.04.

Amazing tool, btw, loving it so far!!

**Comment by marcomeyerVFX** [comment]
That's because streamdeck commands are just simple one-off commands that are not using any shell, much like in a default run-command prompt that you get with<kbd>ALT</kbd>+<kbd>F2</kbd> in Gnome, MATE, etc. . 
So you can't use any fancy shell-specific scripting like `&&`. 

If you want to use shell scripting you have to wrap it in a command for your shell. like this:
```bash
bash -c "wmctrl -a firefox  && xdotool key alt+1"
```

**Comment by lhayhurst** [comment]
Very cool, ty. Closing issue.

**Comment by lhayhurst** [comment]
I've created [a PR with this example](https://github.com/timothycrosley/streamdeck-ui/pull/133).
