### ISSUE TITLE
Stream Deck UI keeps lagging

### ISSUE THREAD

**Issue by Johnnyreyman** [timothycrosley/streamdeck-ui#165]
The deck and the GUI keep freezing on the page after I add an image. It also takes 3 minutes for the program to respond.

**Comment by Johnnyreyman** [comment]
It just freezes in general use now.

**Comment by Semperverus** [comment]
I am having this same issue but on a fresh install, no images loaded. It takes about a minute to three minutes to see any change in the window, and even in a child window such as the XDG dialogue for picking files for the images.

**Comment by dodgyrabbit** [comment]
I would recommend making a copy of ~/.streamdeck_ui.json and then deleting the original.
It is possible that something in the config (images or otherwise) is causing the problem.
If not - please reopen this issue and add as much detail as possible how to reproduce, as well as your specific setup details (operating system, streamdeck version or anything else you think relevant).
