### ISSUE TITLE
What happened to the FLATPAK creation attempt? Is a flatpak package possible? As is, this software is a nightmare to install 

### ISSUE THREAD

**Issue by heidiwenger** [timothycrosley/streamdeck-ui#210]
To solve the overtly difficult and advanced technical knowledge requirement on installing Stream Deck UI generally on Linux.

My Linux switched streamer friends are flabbercasted before the installation instructions. So am i. I don't know how to help them honestly, and one of them already bought the Elgato Stream Deck as she was told it runs on Linux no problem.

So is a flatpak (or a snap for Ubuntu users for that matter) possible? Or did the project face a "force majeure", it's not possible?

I'm referring to this attempt: https://github.com/timothycrosley/streamdeck-ui/issues/168 and https://github.com/flathub/flathub/pull/2648

Thank you for any word or clarification, future creation attempts.

**Comment by dodgyrabbit** [comment]
> What happened to the FLATPAK creation attempt?

As per your link - an attempt was made but ultimately abandoned due to toolchain difficulties.

 > So is a flatpak (or a snap for Ubuntu users for that matter) possible? 

Possible - I would say so yes. We would need someone with some experience in this field to help out.

> and one of them already bought the Elgato Stream Deck as she was told it runs on Linux no problem.

Respectfully - please do your homework. Elgato does not support Linux and the fact that this project even exists is a bonus. There are other similar projects, there may be others more suitable for you.

I would agree that the installation process is not as easy as a commercial software solution provides. Perhaps we could package it up with pyinstaller and create distribution specific installs.

In the meantime, please open a specific issue - with the details of problems you encountered during the install. This will help the community, who is not getting paid and donating their time to troubleshoot and provide constructive feedback. It is impossible to improve/fix something if the only information we have is "this software is a nightmare to install". If you have suggestions on how to improve the documentation, pull requests will be reviewed.
