### ISSUE TITLE
Press keys only works when app is active

### ISSUE THREAD

**Issue by doppynl** [timothycrosley/streamdeck-ui#218]
I'm trying to configure a key for Discord and configured a key-bind in Discord. When I press this key-bind on my normal keyboard this works both when the discord screen is active and inactive.
But it only works on my StreamDeck when the discord window is active. I've configured this as  as "press keys" in the StreamDeckUI.

Now I can use the command to first activate the discord window, but I want my current window to remain active.

Is there a way to make "press keys" work like I pressed them on my normal keyboard?

Might be a Discord specific thing. 

Setup: Ubuntu 21.10 with Gnome.
streamdeck 0.9.0
pyside2 5.15.2.1
pillow 9.1.0
pynput 1.7.6

I don't think it is a bug, hence the enhancement request. 

Thanks.

**Comment by doppynl** [comment]
I'm aware of the command `wmctrl -xa discord`. I've already got that configured. What I currently have is:

Command: "wmctrl -xa discord"
Press Keys: "delay,ctrl+shift+m"
Write Text: <empty>

Problem with that is that it activates the discord window and I want the active window to not change.

The field "Write Text" would just put the text in the chat-text-field, that is not what I want. I want to mute/un-mute.

**Comment by dodgyrabbit** [comment]
This is generally going to be a problem with a "keystroke emulator" based solution.

A better approach would be to use a Discord API and interact via that. Now granted, you'd need some kind of programming experience (usually fairly basic) in order to do that.

A googled a bit and there does seem to be something exactly like that:
https://github.com/Rapptz/discord.py

You could then execute a say-something.py that interacts with Discord in whatever way you want. 

FYI I've been tinkering with a more modularised system where we can extend streamdeck-ui easily by creating pluggable modules, so the community can for example contribute the Discord feature easily and allow you to do this, but that is a whole other story.

**Comment by dodgyrabbit** [comment]
No specific actions planned here. Closing.
