### ISSUE TITLE
Show text under image instead of overimposed as option

### ISSUE THREAD

**Issue by mihi4** [timothycrosley/streamdeck-ui#245]
The behaviour of the buttons pre-v2 was quite nice and looked better to me.

Could we get an option besides the text either to overimpose or display it alone?

**Comment by dodgyrabbit** [comment]
Can I suggest you allow some space under or above your icons and position the text there if you prefer it that way. With a little bit of tinkering in gimp or some kind of graphics app you can achieve this. Thanks for the feedback. Closing for now.

**Comment by xvelasqu** [comment]
@dodgyrabbit  I also miss having the option to reposition text. Now some "icon + text" buttons are less legible because of the rounded corners of the buttons. Text that looked fine when centered and overlapping the icon now gets distorted on the edges.

Sure I could add text to every icon with an image editor, but I believe the previous feature made this way more convenient.
