### ISSUE TITLE
Error during attach: Could not open HID device.

### ISSUE THREAD

**Issue by IanTrudel** [timothycrosley/streamdeck-ui#250]
**Describe the bug**

The UI worked fine in the first round, but it was blank after closing and reopening. Running from the console output the following message: `Error during attach: Could not open HID device.`

**To Reproduce**
1. Open Streamdeck UI
2. Configure, add buttons/actions, etc.
3. Close
4. Reopen

**Expected behavior**
Should connect to the device and reload the existing configuration.

**Screenshots**
![Capture d’écran du 2022-08-07 18-57-45-NO-SERIAL](https://user-images.githubusercontent.com/8844578/183314448-7c1882f6-49d9-4812-9fbe-1058ea3be7be.png)

![Capture d’écran du 2022-08-07 18-55-51](https://user-images.githubusercontent.com/8844578/183314322-3d5f59b8-06d5-49ad-83c2-8a3e6f6aefd3.png)

**Operating system (please complete the following information)**
 - OS: Arch
 - Desktop environment: Gnome
 - Python version 3.10.5
 - StreamDeck UI 2.0.4
   - streamdeck 0.9.1
   - pyside2 5.15.5
   - pillow 9.2.0
   - pynput 1.7.6

**Stream Deck Version**
 - XL

**Comment by OWKenobi** [comment]
This sometimes happens to me as well. Usually unplugging and replugging the usb of the stream deck fixes the issue. Can you confirm this works for you as well?

An idea would be to try to programmatically detach and reattach the stream deck once this issue pops up.

**Comment by IanTrudel** [comment]
Pressing X is causing the issue in the first place. Some code to detach the device should be written around the X control. Unplugging and replugging the USB cable is working. If you close via File > Exit, it will reopen without a problem, but, unfortunately, Streamdeck is not functional without Streamdeck UI running (we should have a systemd service!)

Perhaps Streamdeck UI could try to reattach (first trying to detach and then attach) if it fails to attach.

**Comment by Data-007** [comment]
> Pressing X is causing the issue in the first place. Some code to detach the device should be written around the X control. we should have a systemd service!
(https://github.com/timothycrosley/streamdeck-ui/issues/189#issuecomment-1012631171)
See above HIH

**Comment by IanTrudel** [comment]
Thank you @Data-007 !

**Comment by dodgyrabbit** [comment]
I'd like to understand what is going on here and have some follow up questions:

> Pressing X is causing the issue in the first place.

By this you mean, closing the window by clicking on this?
![image](https://user-images.githubusercontent.com/518187/184504734-9ce8bc12-6eb2-411b-85e3-4a2897451cf5.png)

> Reopen

Can you elaborate exactly how you are reopening the application? Are you running the streamdeck command again from the terminal?

Additional question:
Do you see an icon like this (or similar) in your OS notification area? Sometimes called the AppIndicator. There may be Arch specific issues here to figure out.
![image](https://user-images.githubusercontent.com/518187/184504834-9c743e59-15c2-49d1-8d54-55a74276fb34.png)

Some more details:
Closing the main window (clicking the X) does not actually close the application. It only hides the window. So it may be that you are in fact starting a new instance of the application, which can't access the device since the previous one already has it open. I'd like to figure out if that is what is going on or not. Maybe you could also troubleshoot this using the ps or htop command?

**Comment by IanTrudel** [comment]
> By this you mean, closing the window by clicking on this?

This is the only thing it could ever mean. :P 

> RE: AppIndicator

It makes a lot of sense now. I didn't have AppIndicator installed (and not a huge fan either). Close should always mean close. Though you guys might consider having a preference for that sort of thing. Your hypothesis is correct where an existing instance was already running despite being "closed," thus preventing opening a new instance.

**Comment by dodgyrabbit** [comment]
> but not on the homepage of the project
Unfortunately I don't have access to update that - it's the source of quite a bit of confusion :(

No fix here. AppIndicator is a requirement for the software to function correctly.

**Comment by ulrichwisser** [comment]
As I wrote above, idProduct=0080 is missing in the gh-pages branch. It is in the README.md, but not on the homepage.
