### ISSUE TITLE
StreamDeck Mini missing

### ISSUE THREAD

**Issue by Berofa** [timothycrosley/streamdeck-ui#263]
Just wantet to tell everyone using a StreamDeck Mini:

In my case the ProductId was 0090 which was missing in the rules.d. Just add the following line if you have the same issue (Cannot connect to HID device):

SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0090", TAG+="uaccess"

**Comment by dodgyrabbit** [comment]
FYI The documentation has been updated with a more forgiving configuration.  Instead of adding a line for each product, **replacing** the contents of `/etc/udev/rules.d/70-streamdeck.rules` with the line below, will provide user access to all USB devices manufactured by Elgato. This has the benefit that future devices will not require a revisit of this file. This is also the recommended way by the upstream streamdeck library.

`SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", TAG+="uaccess"`
