### ISSUE TITLE
Stream Deck XL not recognized unless new ID is included in udev rules

### ISSUE THREAD

**Issue by hoover67** [timothycrosley/streamdeck-ui#275]
I received my Stream Deck XL yesterday and followed the howto setting it up manually. It seems the udev example rules miss the device id for my model which is 008f. 

I fixed the "Cannot bind HID device" error by adding the following line to  the udev rules, reloading them and re-plugging the device: 

`SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="008f", TAG+="uaccess"`

(I determined the correct device Id by using "lsusb"). 

All the best & thanks for your work! 

Uwe

**Comment by swedishmike** [comment]
I _think_ this will be fixed by updating this project to use version 0.9.3 of Streamdeck ( https://github.com/abcminiuser/python-elgato-streamdeck/pull/100 ) which adds support for the XL v2.

Sadly I'm not there yet with how to use Poetry so I'm not sure what the proper way of doing that and committing the PR.

Potentially @timothycrosley could chime in with what he wants done?

**Comment by dodgyrabbit** [comment]
Please update to version 2.0.13 which will support the new XL version.
