### ISSUE TITLE
Begining Of entered text missing on  output

### ISSUE THREAD

**Issue by Data-007** [timothycrosley/streamdeck-ui#303]
Entered text is not displayed correctly in an external application(Discord)

**To Reproduce**
Inclosed below is how the button is configured, there is a line break (enter key)in the text field, the cursor is where the green arrow is.
[StreamDeckFault](https://user-images.githubusercontent.com/53057579/223637252-50aa934f-d909-44d6-85ac-500631283e45.png)

**Expected behaviour**
It used to work that when pressed(button) the text would appear and be submitted in 'Discord'.
However, when pressed I get this in discord ("ood Morning Erik") the 'G' is missing and other beginning letters can be missing.

This is not necessarily tide to a specific version(certainly the last two versions of streamdeck-ui), it just started being a problem Iam famous for saying it, in discord chat.

**Screenshots**
Please see above screenshot.

**Operating system (please complete the following information)**
 - OS: [Arch]
 - Desktop environment: [Plasma]
 
**Stream Deck Version**
 -XL-

**Comment by dodgyrabbit** [comment]
@Data-007 I'm going to have to venture a guess that this is some kind of race condition. Since you have both a command and a text instruction, which happens to run in that order (the program doesn't really make an explicit guarantee that it would do that). I suspect what happens is sometimes when executing the switch command (activating discord), it's not yet ready to accept text but streamdeck_ui is already starting to type.  There is no feedback mechanism to "know" when discord (or any other window for that matter) is ready. There are hacks we can do, like add an arbitrary pause in, but - they won't work in all situations and may even be undesired.

Some possible workarounds:

- Add a space or two in front of your message, that when missed, won't be significant
- Review https://github.com/timothycrosley/streamdeck-ui#examples and perhaps send your discord and an xdotool type command. At least you have some flexibility to add pause etc in between in your control.

Closing as this won't result in direct application changes at this time. 
Thanks

**Comment by Data-007** [comment]
@dodgyrabbit 
Something is wrong here.

I have copied the line from your readme: 
bash -c "wmctrl -a firefox  && xdotool key alt+1" 
changed one item "firefox" to "discord"
bash -c "wmctrl -a discord  && xdotool key alt+1"

Still, the text is missing in the post in discord. 
In fact, while testing while editing the command: field
Any text was divided between the command:Field and discord

Data-007

**Comment by dodgyrabbit** [comment]
I think you are misunderstanding my comment. Copy and pasting that particular command wasn't meant to fix the problem. I'm suggesting an alternative _approach_, which is to not use the _Write Text_ feature in streamdeck_ui at all, but see if you can construct a command that switches and types in a reliable way, and use that instead. The `xdotool type` command seems to be an alternative way to get text to your application. You will have to experiment and test how to construct switching, waiting, typing from the terminal to be reliable. This will need to be done with a series of commands. Once you've got that working - use the Command feature to then send that. 

If that is not something you're interested in pursuing, that's fine. Was just trying to provide some guidance on alternative problem solving approaches.

Hope that clears up what I was saying.
