### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL.ImageQt'

### ISSUE THREAD

**Issue by Razer0123** [timothycrosley/streamdeck-ui#328]
Hello, just installed the program using the Fedora tutorial, got this error

` Traceback (most recent call last):
  File "/home/alessandro/.local/bin/streamdeck", line 5, in <module>
    from streamdeck_ui.gui import start
  File "/home/alessandro/.local/lib/python3.11/site-packages/streamdeck_ui/gui.py", line 17, in <module>
    from streamdeck_ui.api import StreamDeckServer
  File "/home/alessandro/.local/lib/python3.11/site-packages/streamdeck_ui/api.py", line 8, in <module>
    from PIL.ImageQt import ImageQt
ModuleNotFoundError: No module named 'PIL.ImageQt'`

Any idea on how to fix it?

**Comment by Razer0123** [comment]
Fixed with

`pip install pillow --upgrade`

**Comment by tdcam** [comment]
I tried this, and got:

[thomas.cameron@host167 Desktop]$ pip install pillow --upgrade
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pillow in /usr/lib64/python3.11/site-packages (9.4.0)
Collecting pillow
  Downloading Pillow-9.5.0-cp311-cp311-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 22.0 MB/s eta 0:00:00
Installing collected packages: pillow
Successfully installed pillow-9.5.0

[thomas.cameron@host167 Desktop]$ streamdeck
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

Aborted (core dumped)

**Comment by tdcam** [comment]
I added a step, and it worked:

sudo dnf install xcb-util-cursor

Now, after both steps in this ticket, Streamdeck works.
