### ISSUE TITLE
Setup.py install for hidapi ... error under Fedora 31

### ISSUE THREAD

**Issue by moxDevLinux** [timothycrosley/streamdeck-ui#38]
Hello
I'veb got a issue when trying to install using the command `pip3 install streamdeck_ui --user`
I got a linking error : `creating build/lib.linux-x86_64-3.7
  gcc -pthread -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -g build/temp.linux-x86_64-3.7/hid.o build/temp.linux-x86_64-3.7/hidapi/libusb/hid.o -L/usr/lib64 -lusb-1.0 -ludev -lrt -lpython3.7m -o build/lib.linux-x86_64-3.7/hid.cpython-37m-x86_64-linux-gnu.so
  /usr/bin/ld : ne peut trouver -ludev
`

If you know what's going on
Tks
Guillaume

**Comment by parkervcp** [comment]
@moxDevLinux You need to install `libusbx-devel libudev-devel`

**Comment by moxDevLinux** [comment]
Tks
it was the solution for the install
Now I have some trouble with lauching Streamdeck : 
his OSError : The libhidapi-hidraw0 backend is currently blacklisted for StreamDeck devices.
did't found any soluce yet
Guillaume

**Comment by parkervcp** [comment]
You followed the docs right? you may need to add the plugdev group and add your user to it.

**Comment by moxDevLinux** [comment]
Hello
No `plugdev group` under Fedora - It's Ububtu only feature.
But may be a idéa - in the `/etc/udev/rules.d/` there is a plugdev group
`SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"`

I change it with removing the last sentence with no succes 
Guillaume

**Comment by mexigabacho** [comment]
Also, make certain you have all the appropriate 'dev' packages installed.  In particular, on Fedora, make certain you have:

systemd-devel
systemd-udev

Those are needed for the compile (along with others mentioned in the docs).  Also, after you get it running, please let me know if the unit is working for you as I'm able to get things compiled and running and program keys, but key presses produce no result currently for me (under Fedora 31).

**Comment by dodgyrabbit** [comment]
Please see the info [here](https://github.com/timothycrosley/streamdeck-ui/issues/69#issuecomment-809837052).
I believe what was going on is that you needed the -dev packages because under Fedora the hidapi python dependency had to be compiled.

In the upcoming 1.0.3 release, that hidapi _python_ dependency is gone, however, you need to install 
```
sudo dnf install hidapi
```
which is the [OS library](https://github.com/libusb/hidapi).

The documentation has been updated. I'm closing this issue for now, we can review once 1.0.3 is published.
