### ISSUE TITLE
Doesn't resume display after suspend

### ISSUE THREAD

**Issue by cros13** [timothycrosley/streamdeck-ui#4]
Doesn't resume display on the streamdeck after system returns from suspend.

**Comment by xorbital** [comment]
This is an issue too if you disconnect and reconnect the device (it can't reconnect), or start streamdeck without a device attached (just throws an error without starting).
Maybe adding a wrapper around the library would mitigate that?

**Comment by marcomeyerVFX** [comment]
There is a pending PR #83 which provides a systemd script that takes care of this. It worked fine for me, however with the currently suggested pip installation method `--user` I'd have to run the `streamdeck` executable from `~/.local/bin` which is a bad idea for security reason. Additionally it throws like 50+ SELinux Warnings on CentOS8 on resume.

If there's no alternative solution way to get streamdeck-ui to run persistently through suspend/resume cycles I wonder if it would make sense to package the application into a somewhat static binary that can run safely from systemd (using cx_Freeze for example). Because installing it through pip without `--user` isn't a great idea either.

**Comment by dodgyrabbit** [comment]
I've started some work on recovering properly after a suspend and will close this case once a proper fix is in place.
Current approach is to monitor for the failure mode and try to recover the streamdeck. Looks like closing and opening the device works - problem is there is currently no real way to detect the failure using the streamdeck library. I'm going to tinker with that some more and perhaps suggest a PR.

There should be no need to completely restart the UI to recover.

**Comment by oparada1988** [comment]
Can confirm this issue still persists

**Comment by KPKoch** [comment]
+1
This is especially hard as the stream deck consumes so much power I do have it on my eGPU USB, which don't have a switch.
A HW switch solves the issue mostly, but this is no option for many.

**Comment by zen2** [comment]
A simple way is to add a udev rule to not suspend streamdeck usb but that will let it switch on and consume energy.
So I think the proper way to fix this issue is to add specific udev rules to notify streamdeck-ui that usb port go to standby or wake up. Like it streamdeck-ui can reinitialize without the need to be relaunched.
Streamdeck-ui is a user program not a system daemon so a system daemon is not the way to go.

**Comment by dodgyrabbit** [comment]
Version 2.0.4 has been published which uses version streamdeck 0.9.1, which in turn includes this MR https://github.com/abcminiuser/python-elgato-streamdeck/pull/88

It should now be able to detect a suspend/resume cycle and recover from it. Please give it a try, worked in all my testing. If you're having trouble, please feel free to open a new case with all the relevant details to review.

**Comment by Smart-Helper** [comment]
Works like a charm now!
Thank you very much!

**Comment by oparada1988** [comment]
Can confirm it works as well

**Comment by StanSvec** [comment]
Fixed for me too! Well done!
