### ISSUE TITLE
Support the Elgato plugin APIs

### ISSUE THREAD

**Issue by fredemmott** [timothycrosley/streamdeck-ui#53]
This is mostly a JSON websocket protocol for both JS and native plugins; JS plugins run in a Qt JS interpreter which is usable on Linux - or the same hooks could likely be reimplemented.

Native plugins are the same protocol, with port numbers and other initialization stuff passed in argv.

I maintain some windows and mac C++ plugins for the official SDK; I'm likely to make them build on Linux just to make some CI problems simpler - and others are mostly using .net which may be portable with mono. If this ended up being actually useful, that'd be even better :)

**Comment by gregfr** [comment]
Could you provide some links about this? TIA

**Comment by nemec** [comment]
Here's the SDK info @gregfr: https://developer.elgato.com/documentation/stream-deck/sdk/overview/
Use the navigation to the left for the technical details.

Looking at the docs, I think supporting the official plugin protocol will be a daunting task 😅
Doable on a technical level, but the current GUI might need to be replaced since it looks like plugins can provide their own configuration UI in HTML (Property Inspector).

**Comment by dodgyrabbit** [comment]
Realistically this is not going to get done. Nice idea though, but not for a small project with few contributors.
